version: '3.8'
services:
  vpn:
    image: thrnz/docker-wireguard-pia
    hostname: torrents
    volumes:
      - /srv/datastore/docker/piawireguard/pia:/pia
      - /srv/datastore/docker/piawireguard/pia-shared:/pia-shared
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    devices:
      - /dev/net/tun:/dev/net/tun
    container_name: piawireguard
    environment:
      - LOC=ca_toronto
      - USER=p9798466
      - PASS=nnEmPHTZ84
      - LOCAL_NETWORK=10.10.0.0/16
      - PORT_FORWARDING=1
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv6.conf.default.disable_ipv6=1
      - net.ipv6.conf.all.disable_ipv6=1
      - net.ipv6.conf.lo.disable_ipv6=1
    healthcheck:
      test: ping -c 1 www.google.com || exit 1
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      MyMacvlan:
        ipv4_address: 10.10.20.80
    restart: unless-stopped

  socks-proxy:
    image: serjs/go-socks5-proxy
    network_mode: "service:vpn"
    depends_on:
      vpn:
        condition: service_healthy

  deluge4vpn:
    container_name: deluge4vpn-stack
    network_mode: container:piawireguard
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Toronto
      - UMASK=002
      - DELUGE_LOGLEVEL=error
    image: lscr.io/linuxserver/deluge:latest
    ipc: private
    restart: unless-stopped
    volumes:
      - /srv/datastore/docker/piawireguard/pia-shared/port.dat:/pia/forwarded_port
      - /srv/datastore/docker/deluge4vpn:/config
      - /srv/mainpool/media:/download
    depends_on:
      vpn:
        condition: service_healthy

  storm:
    container_name: storm-stack
    network_mode: container:piawireguard
    restart: unless-stopped
    environment:
      - DELUGE_RPC_PORT=58846
      - DELUGE_RPC_VERSION=v2
      - DELUGE_RPC_USERNAME=andrew
      - DELUGE_RPC_PASSWORD=luigina
      - DELUGE_RPC_HOSTNAME=10.10.20.80
    image: ghcr.io/relvacode/storm:latest
    depends_on:
      vpn:
        condition: service_healthy

  socks5:
    image: serjs/go-socks5-proxy
    container_name: socks5
    network_mode: container:piawireguard
    environment:
      - TZ=America/Toronto
      - PROXY_PORT=1080
    restart: unless-stopped
    depends_on:
      vpn:
        condition: service_healthy

  firefox:
    container_name: firefox-stack
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Toronto
    image: linuxserver/firefox:latest
    restart: unless-stopped
    volumes:
      - /srv/datastore/docker/firefox/config:/config
    network_mode: container:piawireguard
    depends_on:
      vpn:
        condition: service_healthy
    deploy:
      resources:
        limits:
          memory: 4096M
        reservations:
          memory: 4096M

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    network_mode: container:piawireguard
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Toronto
      - WEBUI_PORT=8080
    volumes:
      - /srv/datastore/docker/qbittorrent:/config
      - /srv/mainpool/media:/download
      - /srv/datastore/docker/gluetun-pia/forward:/forward
    restart: unless-stopped
    depends_on:
      vpn:
        condition: service_healthy

  qbittorrent-port-forward-file:
    container_name: qbittorrent-port-forward
    environment:
      - QBT_USERNAME=admin
      - QBT_PASSWORD=
      - QBT_ADDR=http://10.10.20.80:8080
      - PORT_FILE=/port-forward/port.dat
    image: docker.io/charlocharlie/qbittorrent-port-forward-file:latest
    volumes:
      - /srv/datastore/docker/piawireguard/pia-shared:/port-forward
      - /srv/datastore/docker/qbt-port-forward:/config
    depends_on:
      vpn:
        condition: service_healthy

networks:
  MyMacvlan:
    external: true
    name: MyMacvlan
